### ISSUE TITLE
Robots.txt getting indexed

### ISSUE THREAD

**Issue by rachelslurs** [jbaubree/sitemap-ts#109]
Hello!

I was wondering what process you recommend for setting the headers [so Google, etc. doesn't index the robots.txt](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag). I am wondering if it's something that can be set in the headers when the robots.txt file gets generated.

Thank you!
Rachel

**Comment by jbaubree** [comment]
Hello @rachelslurs ,

I prefer not to integrate this kind of functionality in this library. I would like to avoid it touching external files like index.html.
You can directly add this <meta> tag in your index.html or depending on your stack, use the appropriate tools like useHead for nuxt, @vueuse/head for vue...
