### ISSUE TITLE
Fix typo error

### ISSUE THREAD

**Issue by ansidev** [jbaubree/sitemap-ts#39]
https://github.com/jbaubree/sitemap-ts/blob/f515bb90c5c750b4e9eec009dd99f773dd5a90e5/src/types.ts#L60

It should be `extensions`.

**Comment by jbaubree** [comment]
Sure, i will fixe this asap

**Comment by jbaubree** [comment]
@ansidev This is fixed in version 1.0.0 with all deps upgrade and vite 3 compatibility
