### ISSUE TITLE
Dynamic routes like /user/[id] generated in sitemap

### ISSUE THREAD

**Issue by ma-joel** [jbaubree/sitemap-ts#61]
when ssg build with options `{"includeAllRoutes": true}` or with a `includedRoutes` function, file like `/user/[id].vue` got generated to `/user/:id.html` , the `exclude` option support string only, so how could i remove these from the result?

**Comment by jbaubree** [comment]
I think you can use exclue: ["/user/:id"] or something like this. If this not work, can you provide me a repo with reproduction ?
Thanks for report

**Comment by ma-joel** [comment]
yes, that could be done, but what if I have a bunch of such files, is there a way that i can do in a batch?

**Comment by jbaubree** [comment]
Maybe you can use `fast-glob` sync function with regex to automatically get all your dynamic routes. You can check this example to find routes:
https://github.com/jbaubree/sitemap-ts/blob/5743ece89e11540bad098331c47f2f1c8e893b5f/src/sitemap.ts#L12

**Comment by ma-joel** [comment]
Thanks @jbaubree, this works
