### ISSUE TITLE
Ability to add base path

### ISSUE THREAD

**Issue by flauwekeul** [jbaubree/sitemap-ts#62]
Hi! I'm using your library to generate a sitemap for a VitePress site (https://abbekeultjes.nl/honeycomb). I'd like to be able to generate links in the sitemap for a hostname **and** base path (not sure if that's the best name): `https://abbekeultjes.nl/honeycomb/`. When I pass that url for the `hostname` option, the `/honeycomb/` part is removed. This makes sense, since it's not part of the hostname.

Could you add an option to specify any path elements that get appended to the hostname?

Thanks!

**Comment by jbaubree** [comment]
Hi,
Thanks for your report, i will check this out as soon as posible.

**Comment by jbaubree** [comment]
You can try `v1.2.0` with basePath option. This will normally fix your issue. If you get any trouble with this, feel free to come back to me.

**Comment by flauwekeul** [comment]
Thanks! Works like a charm 👌
