### ISSUE TITLE
Error during lint-staged in vitest.config.ts file

### ISSUE THREAD

**Issue by mikezotovdev** [jbaubree/sitemap-ts#72]
Hi! I'm about to create a MR to your repo with a new feature, but I encountered an error during `lint-staged` check run. The error is reproducible on the current master version of your repo, so probably it's not subject to my MR.

It seems to me, the config is written incorrectly, and there are some articles how to configure vitest.config.ts - all of them suggest another structure - code below (some articles - [one](https://dev.to/marabesi/configuring-vitest-and-testing-library-to-work-together-4knn), [two](https://stackoverflow.com/questions/74175246/vitest-global-variables-in-setupfiles), [three](https://cathalmacdonnacha.com/migrating-from-jest-to-vitest)). However, if I try to use the following code, nothing happens (just an empty output...or maybe it's the expected behavior?)

_vitest.config.ts file_
```
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    name: 'config',
    setupFiles: 'test/setup.ts',
  },
})

```

Here is what happen with the old config file. Simply speaking, the type is wrong.
Just open file (I use WebStorm) and see that:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/19310207/231794176-b0226b60-86f8-476c-991e-d3f69a37720a.png">

Console after manual run of `tsc --skipLibCheck --noEmit`

<img width="971" alt="image" src="https://user-images.githubusercontent.com/19310207/231794290-f1fa9364-0137-4766-8d8b-6e4f3eba5777.png">

If I run my code with a possible fix:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/19310207/231797437-fca6402c-54e9-4eda-8e7f-b30a67714aca.png">

FYI: I use yarn, TS 4.9.4.

Could you help me to figure out that issue? Thanks!

**Comment by mikezotovdev** [comment]
@jbaubree

**Comment by jbaubree** [comment]
Hello @mikezotovdev. Sorry for late answer, i have a lot in my plates. Can you try to use pnpm to install project dependencies ? I have no problem with `pnpm test` or `pnpm typecheck` in my side

**Comment by jbaubree** [comment]
@mikezotovdev anyway, i have updated my vitest config with new format if it can help you

**Comment by mikezotovdev** [comment]
Thanks, @jbaubree, now my IDE doesn't show any error. I'll close that ticket.

**Comment by jbaubree** [comment]
Thanks @mikezotovdev i'll take a look at your PR on next week.
