### ISSUE TITLE
Does not append dynamic routes

### ISSUE THREAD

**Issue by mjlehrke** [jbaubree/sitemap-ts#75]
Hello,

Version 0.4.0 broke this package. Version 0.3.0 works properly.

Recently, the sitemap output does not correctly append the dynamic route. Instead, it just puts 'route' at the end of each item.

For instance, this is what happens when I give `dynamicRoutes: ['/about']` as an option:
```xml
    <url>
        <loc>
            https://example.com/route
        </loc>
        <lastmod>
            2023-05-06T04:35:50.973Z
        </lastmod>
        <changefreq>
            daily
        </changefreq>
        <priority>
            1.0
        </priority>
    </url>
```

**Comment by jbaubree** [comment]
hi @mjlehrke. Thanks for your feedback, can you give me a repo with minimal repro of your issue ?

**Comment by jbaubree** [comment]
@mjlehrke normaly `sitemap-ts` `v1.4.0` fix your issue. Can you confirm it?

**Comment by mjlehrke** [comment]
That seems to have fixed it, thanks.
