### ISSUE TITLE
Allow multiple Sitemap configs in robots.txt

### ISSUE THREAD

**Issue by ericuldall** [jbaubree/sitemap-ts#91]
See details in this issue: https://github.com/jbaubree/vite-plugin-sitemap/issues/59

Can we get an option to add additional sitemap endpoints that may be generated by other means?
Example:
```
{
  additionalSitemaps: [
    'https://example.com/sitemap2.xml',
    'https://example.com/sitemap3.xml',
  ]
}
```

**Comment by jbaubree** [comment]
https://github.com/jbaubree/vite-plugin-sitemap/issues/59#issuecomment-1815810509
